### ISSUE TITLE
您好，运行时候显示这样的错误

### ISSUE THREAD

**Issue by yangninghua** [wangtao0101/vscode-debug-leetcode#1]
unable to start debugging 路径中具有非法字符

**Comment by wangtao0101** [comment]
@yangninghua debug面板会有很详细的信息，你可以贴出来看看

**Comment by yangninghua** [comment]
是指这个吗？launch.jsom
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "g++.exe build and debug active file",
        "type": "cppdbg",
        "request": "launch",
        "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": false,
        "MIMode": "gdb",
        "miDebuggerPath": "D:\\mingw64\\bin\\gdb.exe",
        "setupCommands": [
          {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
          }
        ],
        "preLaunchTask": "g++.exe build active file"
      }
    ]
  }
```

**Comment by wangtao0101** [comment]
@yangninghua 这个插件不需要任何launch.json文件，点文件的debug就好了

**Comment by yangninghua** [comment]
博主，我这边一点击debug，就会弹出
![image](https://user-images.githubusercontent.com/32252319/79942755-25aac500-849a-11ea-906d-e1677314e987.png)
![image](https://user-images.githubusercontent.com/32252319/79942772-2d6a6980-849a-11ea-8eb0-7a620f5e456e.png)

**Comment by wangtao0101** [comment]
检查一下你的 ~/AppData\Roaming\Code\User\globalStorage\wangtao0101.debug-leetcode这个路径在不在，在的话全路径是多少，这个路径内有啥文件

**Comment by yangninghua** [comment]
您好，这是文件列表
![image](https://user-images.githubusercontent.com/32252319/79943338-3576d900-849b-11ea-8f9b-01ffaf87ed75.png)

**Comment by wangtao0101** [comment]
全路径呢

**Comment by yangninghua** [comment]
C:\Users\25629\AppData\Roaming\Code\User\globalStorage\wangtao0101.debug-leetcode

我需要加入到window的path吗

**Comment by wangtao0101** [comment]
gdb g++ 都放入window path了吗

**Comment by yangninghua** [comment]
大佬，都放入了，你用的也是windows吗？

**Comment by yangninghua** [comment]
我把所有的.h和.cpp全部放入当前路径下了，还是提示我
unable to start debugging 路径中具有非法字符
但是我都没有launch.json

**Comment by wangtao0101** [comment]
我用window 10，你这路径也没啥非法字符啊

**Comment by yangninghua** [comment]
估计vscode版本问题，我再下载个新的试试

**Comment by wangtao0101** [comment]
如果还是不行的话，试试把下面这个文件的gdb.exe改成绝对路径试试
~/.vscode\extensions\wangtao0101.debug-leetcode-0.2.2\out\src\debug\executor\cppExecutor.js
![gdb](https://user-images.githubusercontent.com/2182570/79944750-eb8ff200-849e-11ea-8d96-71acbd6232b2.png)

**Comment by yangninghua** [comment]
成功了ლ(´ڡ`ლ)

**Comment by wangtao0101** [comment]
什么原因

**Comment by yangninghua** [comment]
就按照刚刚说的，但是具体为什么我没明白，按理说我的路径是对的
![image](https://user-images.githubusercontent.com/32252319/79945189-dd8ea100-849f-11ea-80d5-c89d312f5cfe.png)

**Comment by wangtao0101** [comment]
万分感谢，说明有些系统不支持使用path中的gdb，只能用绝对路径，所以我的插件需要添加一个miDebugerPath的配置，用户可以配置。   你这个方法只能临时用用，下次插件一升级就没了

**Comment by yangninghua** [comment]
大佬我应该感谢您，debug好认真，有可能我不是zhengban系统，之前买来电脑自己加固态做掉了，我觉得有可能是这样，我看网上很多因为不是zhengban系统导致的锅

**Comment by wangtao0101** [comment]
能否告知一下mingw的版本，看看是不是这个原因

**Comment by yangninghua** [comment]
x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0下载的是这个
下载地址：
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/sjlj/x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0.7z/download

**Comment by yangninghua** [comment]
您好我最近想在ubuntu上尝试下这个工具，但是
出现如下问题：
```
                     ^
/home/boyun/.config/Code/User/globalStorage/wangtao0101.debug-leetcode/commoncppproblem1.cpp: In function ‘std::vector<cJSON*> parsecJSONArray(const cJSON*)’:
/home/boyun/.config/Code/User/globalStorage/wangtao0101.debug-leetcode/commoncppproblem1.cpp:284:24: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
     vector<cJSON *> res{};
                        ^
/home/boyun/.config/Code/User/globalStorage/wangtao0101.debug-leetcode/commoncppproblem1.cpp:284:25: error: in C++98 ‘res’ must be initialized by constructor, not by ‘{...}’
     vector<cJSON *> res{};
```

**Comment by yangninghua** [comment]
默认是，gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

**Comment by yangninghua** [comment]
我切换了7.0版本的gcc 显示了新错误：
```
In file included from /home/boyun/.config/Code/User/globalStorage/wangtao0101.debug-leetcode/cppproblem1.cpp:12:0:
/home/boyun/.config/Code/User/globalStorage/wangtao0101.debug-leetcode/sourcecppproblem1.cpp: In member function ‘std::vector<int> Solution::twoSum(std::vector<int>&, int)’:
/home/boyun/.config/Code/User/globalStorage/wangtao0101.debug-leetcode/sourcecppproblem1.cpp:19:9: error: ‘unordered_map’ was not declared in this scope
         unordered_map<int, int> m;
         ^~~~~~~~~~~~~
/home/boyun/.config/Code/User/globalStorage/wangtao0101.debug-leetcode/sourcecppproblem1.cpp:19:23: error: expected primary-expression before ‘int’
         unordered_map<int, int> m;
                       ^~~
/home/boyun/.config/Code/User/globalStorage/wangtao0101.debug-leetcode/sourcecppproblem1.cpp:22:13: error: ‘m’ was not declared in this scope
             m[nums[i]] = i;
             ^
/home/boyun/.config/Code/User/globalStorage/wangtao0101.debug-leetcode/sourcecppproblem1.cpp:22:13: note: suggested alternative: ‘tm’
             m[nums[i]] = i;
             ^
             tm
/home/boyun/.config/Code/User/globalStorage/wangtao0101.debug-leetcode/sourcecppproblem1.cpp:26:17: error: ‘m’ was not declared in this scope
             if (m.count(t) && m[t] != i) {
                 ^
/home/boyun/.config/Code/User/globalStorage/wangtao0101.debug-leetcode/sourcecppproblem1.cpp:26:17: note: suggested alternative: ‘tm’
             if (m.count(t) && m[t] != i) {
                 ^
                 tm
```

**Comment by yangninghua** [comment]
找到了错误，原因是gcc版本太低，我的例子中使用了unordered_map，gcc5.4不支持，我切换了gcc7就好了
```
        unordered_map<int, int> m;
        vector<int> res;
        for (int i = 0; i < nums.size(); ++i) {
            m[nums[i]] = i;
        }
        for (int i = 0; i < nums.size(); ++i) {
            int t = target - nums[i];
            if (m.count(t) && m[t] != i) {
                res.push_back(i);
                res.push_back(m[t]);
                break;
            }
        }
        return res;    
    }
```

**Comment by yangninghua** [comment]
或者gcc5.4,在文件
vim ~/.vscode/extensions/wangtao0101.debug-leetcode-0.2.2/out/src/debug/executor/cppExecutor.js 
中加入
-std=c++11
![image](https://user-images.githubusercontent.com/32252319/88359408-14c56480-cda5-11ea-8bec-d0e47d178552.png)

**Comment by wangpeng-wp** [comment]
大佬，我想问下我这报错是什么原因
Error: Command "g++ -g,c:\Users\58477\AppData\Roaming\Code\User\globalStorage\wangtao0101.debug-leetcode\cppproblem1.cpp,c:\Users\58477\AppData\Roaming\Code\User\globalStorage\wangtao0101.debug-leetcode\commoncppproblem1.cpp,c:\Users\58477\.vscode\extensions\wangtao0101.debug-leetcode-0.2.3\src\debug\thirdparty\c\cJSON.c,-o,c:\Users\58477\AppData\Roaming\Code\User\globalStorage\wangtao0101.debug-leetcode\cppproblem1.exe,-I,c:\Users\58477\AppData\Roaming\Code\User\globalStorage\wangtao0101.debug-leetcode,-I,c:\Users\58477\.vscode\extensions\wangtao0101.debug-leetcode-0.2.3\src\debug\thirdparty\c" failed with exit code "1".
	at ChildProcess.<anonymous> (c:\Users\58477\.vscode\extensions\wangtao0101.debug-leetcode-0.2.3\out\src\utils\cpUtils.js:29:35)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by lvl-coding** [comment]
哈喽@wangtao0101，想问一下
![image](https://github.com/user-attachments/assets/c639a7b5-7c8b-442a-9cf2-46455cb94ffc)
路径已存在但是提示不存在，是由于路径中分隔符为\\的原因吗，我在地址栏输入\\为分隔符的路径也会提示不存在，这个如何解决呢
